version: "1"

services:
  sonarqube:
    image: sonarqube:community
    depends_on:
      - sonardb
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonardb:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: qq99ab
    volumes:
      - /home/admin/sonarqube_data:/opt/sonarqube/data
      - /home/admin/sonarqube_extensions:/opt/sonarqube/extensions
      - /home/admin/sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"
    networks:
      sonar-net:
        ipv4_address: 172.30.0.2
    restart: always
    
  sonardb:
    image: postgres
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: qq99ab
    volumes:
      - /home/admin/postgresql:/var/lib/postgresql
      - /home/admin/postgresql/postgresql_data:/var/lib/postgresql/data
    networks:
      sonar-net:
        ipv4_address: 172.30.0.8
    restart: always
networks:
  sonar-net:
    driver: bridge
    ipam:
     config:
       - subnet: 172.30.0.0/16
         gateway: 172.30.0.1
